server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak_trial
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-backend
            client-secret: "zSlPbz315NKBrAaixfTEFHP08DVyNMfh"
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:4000/realms/myRealm
            authorization-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/auth
            token-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/token
            user-info-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:4000/realms/myRealm/protocol/openid-connect/certs

      resourceserver:
        jwt:
          issuer-uri: http://localhost:4000/realms/myRealm
  data:
    mongodb:
      database: traveler_db
      uri: mongodb://localhost:23017/traveler_db
      host: localhost
      port: 23017

jwt:
  auth:
    converter:
      resource-id: spring-backend
      principle-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG

authentication-type: "implicit"

output.dir: src/test/java/generated

project_path: C:\Users\sunhi\IdeaProjects\rasp-backend
content_root_package_path: \\src/main/java/com/rasp/app
reference_package_path: com.rasp.app
generate_resource_path: C:\Users\sunhi\OneDrive\Desktop\RASP_Designer\generated_backends
clientId: "admission-rest-api"
clientSecret: "6neWV6pfJVKKKgEuAqpYtUSO5a4br9fB" # Replace with your actual secret
keycloakTokenUrl: "http://localhost:4000/realms/myRealm/protocol/openid-connect/token"
keycloakUrl: "http://localhost:4000/admin/realms/myRealm"
ResourcePack: "com.rasp.app.resource"
HelperPack: "com.rasp.app.helper"

# Admin configuration
admin:
  secret:
    password: "admin@123"  # Default admin secret password


